#!/usr/bin/env python3

import warnings
warnings.filterwarnings("ignore")
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
from scipy.ndimage import imread
from canvas import canvasUI
from keras.models import load_model
from pickle import load

model = load_model("utils/model.h5")
with open("utils/scaler.pickle", "rb") as fh:
    scaler = load(fh)

alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

ch = 'y'
while ch=='y':
    canvasUI()
    img = imread('utils/temp.jpg', flatten=True)
    img = (255.0 - img)
    img.shape = (1, 784)
    img = scaler.transform(img)
    img.shape = (1,28,28,1)
    if (img == 0).all():
        print("NO INPUT GIVEN!")
    else:
        AL = model.predict(img)[0]
        pred = AL.argmax()
        conf = 100 * AL[pred].squeeze()/np.sum(AL)
        print("Prediction:", alphabet[pred],'\tConfidence:',round(conf,5),'%\n')
    ch = input("Want to try again?([y]/n):").strip().lower()
    if ch!='y':
        print("Aborting...")
        break
